Form structure
sneeu-leeu/Building-Forms-CSS-HTML pull request #3
Opened 2020-08-19 09:44 UTC by sneeu-leeu

## A clone of the Mint.com sign up page

#### In this project we learned:
* to create a page to display and input data

2020-08-19 17:16 UTC, santiagorodriguezbermudez requested changes
# Changes Required ♻️

Nice work so far! The page is looking good. 🚀🚀🚀

Please address the following changes:

- [x] Your Pull Request and Commits must be improved. Remember that both must have a descriptive language. In your case you have repeated the name of a couple of commits:

- 'Image' is used twice
- 'changed form footer' is also twice
- 'form-setup' as well. 

Kindly change the name of those commits to make them more descriptive according to the changes they each represent. Check out this tutorial for such think: [How to rebase past commits](https://help.github.com/en/github/using-git/about-git-rebase)

- [x] Your Pull Request must be more descriptive. Describe what are the things that you worked and implemented on the PR. 

- [x] Linters are not working properly. Please setup the linters for this project. Follow the tutorial linked on the project specifications: [Setup Github Actions (aka linters)](https://github.com/microverseinc/linters-config/tree/master/html-css)

- [x] Your top right bottom should be on the corner. Delete the right padding and adjust the color so that it similar to the original project. 
![Screen Shot 2020-08-19 at 11 53 29 AM](https://user-images.githubusercontent.com/5817056/90666168-9d072000-e212-11ea-9db8-300d497a1bd0.png)

- [x] Your logos are not centralized horizontally nor vertically align with their corresponding text. Align horizontally and vertically. 
![Screen Shot 2020-08-19 at 11 57 51 AM](https://user-images.githubusercontent.com/5817056/90666606-3e8e7180-e213-11ea-83da-1517bfca3511.png)

- [x] Footer should be below the form and not at the button according to the original page.
![Screen Shot 2020-08-19 at 12 00 28 PM](https://user-images.githubusercontent.com/5817056/90666835-96c57380-e213-11ea-9115-dde3463402ac.png)

- [x] Do not use inline styling change the referred style below on your HTML file. 

- [x] Change the footer to be part of your body tags. 

- [x] The width of the form should be a bit smaller according to the original project.

- [ ] [OPTIONAL]: Nice work deploying on Netlify this will help you out in the future. However, for the purpose of simplicity, I strongly suggest you use [Githack](https://raw.githack.com/) for upcoming projects as it is way simpler and you can focus on learning the core HTML concepts. 

Happy coding 👨🏻‍💻 👩‍💻
If you have additional questions, feel free to reach out on slack @santiagorodriguezb

2020-08-19 17:16 UTC, santiagorodriguezbermudez commented on Index.html
> +</footer>
- [ ] The footer must be inside the body tags. Kindly move it at the end of the body tags.

2020-08-19 17:16 UTC, santiagorodriguezbermudez commented on Index.html
> +                <small style="color: blue">I forgot my User ID or Password</small>
- [ ] Do not use inline styling. Rather, implement this on your CSS file to keep everything organized.

2020-08-20 18:32 UTC, Spayco requested changes
# Changes Requested 

Hello Team! 👋 

Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

first off, your page looks messed up on my screen unless I change my chrome size, but I understand this is because we have different screen sizes, please let future TSEs who review your projects know through the PR post next time for less confusion, you can also take it a step further and style your page with responsive units such as the [percentage or viewport units](https://www.w3schools.com/cssref/css_units.asp)!

- [ ] you have **20** errors from the [HTML Validator](https://validator.w3.org/#validate_by_upload), please fix them

- [ ] fix your linting errors please!

- **more changes below**





### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-20 18:32 UTC, Spayco commented on Index.html
> +    </ul>
- [ ] these should be links

2020-08-20 20:17 UTC, Spayco approved these changes
## Project Approved ✔️ 

Good Job making the changes required! don't forget to merge and good luck with your next projects! 


Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

2020-08-21 09:15 UTC, merged